import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Carousel from "./components/carousel";

import React from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gradient-to-r from-blue-400 to-purple-600 flex flex-col items-center justify-center"><Navbar/><Carousel/>{children}</body>
    </html>
  );
}